-- Discount fields: line + document level (fixed AED or percent)

ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "lineDiscountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
UPDATE "Quotation" SET "discountMode" = 'fixed', "discountValue" = "discount" WHERE "discount" > 0;

ALTER TABLE "QuotationLine" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "QuotationLine" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "QuotationSection" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "QuotationSection" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "QuotationSectionItem" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "QuotationSectionItem" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "lineDiscountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "InvoiceLine" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "InvoiceLine" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Lpo" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Lpo" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Lpo" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Lpo" ADD COLUMN IF NOT EXISTS "lineDiscountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "LpoLine" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "LpoLine" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "lineDiscountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PurchaseInvoiceLine" ADD COLUMN IF NOT EXISTS "discountMode" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "PurchaseInvoiceLine" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
