import { StyleSheet } from '@react-pdf/renderer';

export const palette = {
  ink: '#14202b',
  muted: '#5d6b78',
  soft: '#8a949e',
  accent: '#1a6b7a',
  line: '#dfe4e8',
  wash: '#f4f6f8',
  danger: '#c23b3b',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontSize: 9.5,
    color: palette.ink,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 22,
  },
  logo: { width: 108, height: 44, objectFit: 'contain' },
  companyName: { fontSize: 15, fontFamily: 'Helvetica-Bold' },
  companyLine: { color: palette.muted, marginTop: 2 },
  docBlock: { alignItems: 'flex-end' },
  docTitle: {
    fontSize: 17,
    fontFamily: 'Helvetica-Bold',
    color: palette.accent,
    letterSpacing: 0.5,
  },
  docNumber: { marginTop: 4, fontFamily: 'Helvetica-Bold' },
  docMeta: { color: palette.muted, marginTop: 2 },
  parties: { flexDirection: 'row', gap: 18, marginBottom: 18 },
  party: {
    flex: 1,
    backgroundColor: palette.wash,
    borderRadius: 4,
    padding: 10,
  },
  partyLabel: {
    fontSize: 7.5,
    color: palette.accent,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.7,
    marginBottom: 4,
  },
  partyName: { fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  partyLine: { color: palette.muted, lineHeight: 1.4 },
  tableHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.ink,
    paddingBottom: 5,
    marginBottom: 2,
  },
  headCell: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
    color: palette.ink,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingVertical: 6,
    alignItems: 'flex-start',
  },
  cellDescription: { flex: 1, paddingRight: 8 },
  cellThumb: { width: 38, height: 30, objectFit: 'cover', borderRadius: 2 },
  thumbHolder: { width: 46 },
  cellUnit: { width: 42 },
  cellQty: { width: 46, textAlign: 'right' },
  cellPrice: { width: 68, textAlign: 'right' },
  cellTotal: { width: 74, textAlign: 'right' },
  lineDescription: { lineHeight: 1.35 },
  totals: { marginTop: 14, flexDirection: 'row', justifyContent: 'flex-end' },
  totalsBox: { width: 230 },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  totalLabel: { color: palette.muted },
  totalValue: { textAlign: 'right' },
  grandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: palette.ink,
    marginTop: 4,
    paddingTop: 5,
  },
  grandLabel: { fontFamily: 'Helvetica-Bold' },
  grandValue: { fontFamily: 'Helvetica-Bold', textAlign: 'right' },
  section: { marginTop: 18 },
  sectionTitle: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.7,
    color: palette.accent,
    marginBottom: 4,
  },
  bodyText: { color: palette.muted, lineHeight: 1.45 },
  signatureRow: {
    marginTop: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  signature: { width: 130, height: 46, objectFit: 'contain' },
  signatureLabel: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: palette.muted,
    paddingTop: 3,
    color: palette.muted,
    width: 150,
  },
  watermark: {
    position: 'absolute',
    top: 300,
    left: 120,
    fontSize: 62,
    color: palette.danger,
    opacity: 0.14,
    fontFamily: 'Helvetica-Bold',
    transform: 'rotate(-24deg)',
  },
  footer: {
    position: 'absolute',
    bottom: 26,
    left: 40,
    right: 40,
    fontSize: 7.5,
    color: palette.soft,
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: palette.line,
    paddingTop: 6,
  },
});
