import { StyleSheet } from '@react-pdf/renderer';

export const palette = {
  ink: '#14202b',
  muted: '#5d6b78',
  soft: '#8a949e',
  accent: '#1a6b7a',
  line: '#dfe4e8',
  wash: '#f4f6f8',
  danger: '#c23b3b',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontSize: 9.5,
    color: palette.ink,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 22,
  },
  logo: { width: 108, height: 44, objectFit: 'contain' },
  companyName: { fontSize: 15, fontFamily: 'Helvetica-Bold' },
  companyLine: { color: palette.muted, fontSize: 9.5, marginTop: 1 },
  docBlock: { alignItems: 'flex-end' },
  docTitle: {
    fontSize: 17,
    fontFamily: 'Helvetica-Bold',
    color: palette.accent,
    letterSpacing: 0.5,
  },
  docNumber: { marginTop: 3, fontFamily: 'Helvetica-Bold', fontSize: 9.5 },
  docMeta: { color: palette.muted, fontSize: 9.5, marginTop: 1 },
  parties: { flexDirection: 'row', gap: 18, marginBottom: 18 },
  party: {
    flex: 1,
    backgroundColor: palette.wash,
    borderRadius: 4,
    padding: 10,
  },
  partyLabel: {
    fontSize: 7.5,
    color: palette.accent,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.7,
    marginBottom: 4,
  },
  partyName: { fontFamily: 'Helvetica-Bold', fontSize: 9.5, marginBottom: 1 },
  partyLine: { color: palette.muted, fontSize: 9.5, marginTop: 1 },
  tableHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.ink,
    paddingBottom: 5,
    marginBottom: 2,
  },
  headCell: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
    color: palette.ink,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingVertical: 6,
    alignItems: 'flex-start',
  },
  cellDescription: { flex: 1, paddingRight: 8 },
  cellThumb: { width: 38, height: 30, objectFit: 'cover', borderRadius: 2 },
  thumbHolder: { width: 46 },
  cellUnit: { width: 42, textAlign: 'left' },
  cellQty: { width: 46, textAlign: 'right' },
  cellPrice: { width: 68, textAlign: 'right' },
  cellTotal: { width: 74, textAlign: 'right' },
  lineDescription: { lineHeight: 1.35 },
  totals: { marginTop: 14, flexDirection: 'row', justifyContent: 'flex-end' },
  totalsBox: { width: 230 },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  totalLabel: { color: palette.muted },
  totalValue: { textAlign: 'right' },
  grandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: palette.ink,
    marginTop: 4,
    paddingTop: 5,
  },
  grandLabel: { fontFamily: 'Helvetica-Bold' },
  grandValue: { fontFamily: 'Helvetica-Bold', textAlign: 'right' },
  section: { marginTop: 18 },
  sectionTitle: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.7,
    color: palette.accent,
    marginBottom: 4,
  },
  bodyText: { color: palette.muted, lineHeight: 1.45 },
  signatureRow: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 24,
  },
  clientSignatureCol: {
    width: '48%',
    maxWidth: 260,
  },
  issuerSignatureCol: {
    width: '48%',
    maxWidth: 220,
    alignItems: 'flex-end',
  },
  clientSigRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  clientSigLabel: {
    width: 72,
    fontSize: 8.5,
    color: palette.muted,
    paddingBottom: 2,
  },
  clientSigLine: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: palette.muted,
    height: 14,
  },
  signature: { width: 130, height: 46, objectFit: 'contain' },
  signaturePlaceholder: { width: 130, height: 46 },
  signatureLabel: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: palette.muted,
    paddingTop: 3,
    color: palette.muted,
    width: 150,
    textAlign: 'right',
    fontSize: 8.5,
  },
  watermark: {
    position: 'absolute',
    top: 300,
    left: 120,
    fontSize: 62,
    color: palette.danger,
    opacity: 0.14,
    fontFamily: 'Helvetica-Bold',
    transform: 'rotate(-24deg)',
  },
  footer: {
    position: 'absolute',
    bottom: 26,
    left: 40,
    right: 40,
    fontSize: 7.5,
    color: palette.soft,
    textAlign: 'right',
    borderTopWidth: 1,
    borderTopColor: palette.line,
    paddingTop: 6,
  },
  /** Compact letterhead stacks — single-spacing, not sibling-Text gaps. */
  ctIntro: { marginBottom: 8 },
  ctIntroBlock: { fontSize: 9.5, marginBottom: 6 },
  ctSection: { marginTop: 8, marginBottom: 4 },
  ctSectionTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  ctSpecRow: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: 1.5,
    borderBottomWidth: 0.5,
    borderBottomColor: palette.line,
  },
  ctSpecLabelText: {
    width: '42%',
    textAlign: 'left',
    color: palette.muted,
    paddingRight: 8,
  },
  ctSpecValueText: {
    width: '58%',
    textAlign: 'right',
  },
  ctAmountRow: {
    flexDirection: 'row',
    width: '100%',
    paddingTop: 4,
    marginTop: 2,
    borderTopWidth: 1,
    borderTopColor: palette.ink,
  },
  ctAmountText: { fontFamily: 'Helvetica-Bold', color: palette.ink },
  ctAmountNumber: { fontFamily: 'Helvetica-Bold' },
  ctNotes: { marginTop: 8, marginBottom: 4, lineHeight: 1.35, color: palette.muted, fontSize: 8.5 },
  ctTotalsWrap: { marginTop: 6, flexDirection: 'row', justifyContent: 'flex-end' },
  ctTotalsBox: { width: 220 },
  ctCompactSection: { marginTop: 6 },
  ctTermsBody: { color: palette.muted, lineHeight: 1.3, fontSize: 8.5 },
  genThankYouWrap: { marginTop: 8 },
  genIntro: { marginBottom: 8 },
  genIntroBlock: { fontSize: 9.5 },
  genTableHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.ink,
    paddingBottom: 4,
    marginTop: 4,
    marginBottom: 2,
  },
  genRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingVertical: 5,
    alignItems: 'flex-start',
  },
  genCellSn: { width: 20, textAlign: 'center', paddingTop: 2 },
  genCellPicture: { width: 46, textAlign: 'center' },
  genCellQty: { width: 76, textAlign: 'right', paddingRight: 4 },
  genCellRate: { width: 58, textAlign: 'right', paddingRight: 4 },
  genCellTotal: { width: 68, textAlign: 'right' },
  genHeadCell: {
    fontSize: 7.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
    color: palette.ink,
  },
  genThankYou: {
    marginTop: 8,
    fontSize: 8.5,
    color: palette.muted,
    lineHeight: 1.35,
  },
  genDisclaimer: {
    marginTop: 4,
    fontSize: 8,
    color: palette.soft,
    lineHeight: 1.3,
  },
});
