import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#fafbfc',
  surface: '#ffffff',
  ink: '#0f2744',
  primary: '#0f2744',
  primaryMid: '#1a3a5c',
  muted: '#5c6b7a',
  soft: '#94a3b8',
  accent: '#2563eb',
  accentSoft: '#eff6ff',
  accentStrong: '#1d4ed8',
  gold: '#c9a227',
  line: '#e8ecf1',
  danger: '#c23b3b',
};

export const ui = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    padding: 16,
    paddingBottom: 48,
  },
  title: {
    color: colors.ink,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  lede: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    marginBottom: 2,
  },
  count: {
    color: colors.soft,
    fontSize: 13,
  },
  button: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
  ghost: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  ghostText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
  },
  dangerText: {
    color: colors.danger,
  },
  /** Form / detail cards — keep roomy. List rows use RecordRow instead. */
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginTop: 10,
    width: '100%',
    alignSelf: 'stretch',
  },
  cardTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '600',
  },
  cardMeta: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 3,
    lineHeight: 18,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  label: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.ink,
    width: '100%',
    alignSelf: 'stretch',
    minHeight: 48,
  },
  error: {
    color: colors.danger,
    marginTop: 12,
    fontSize: 14,
  },
  empty: {
    marginTop: 16,
    padding: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.line,
    alignItems: 'center',
  },
  emptyText: {
    color: colors.muted,
    textAlign: 'center',
  },
  tag: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
    color: colors.accent,
    fontSize: 11,
    fontWeight: '600',
    overflow: 'hidden',
  },
});
